name: Distribute to server

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Build_and_distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: lucys.r-e.kr
          username: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_USER_PASSWORD }}
          protocol: ftps
          local-dir: .
          server-dir: ./celestial/
